/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMOTE_H_RPCGEN
#define _REMOTE_H_RPCGEN

#include <tirpc/rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define WHO_PROG 0x20000001
#define WHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define WHO_PROC 1
extern  char ** who_proc_1(void *, CLIENT *);
extern  char ** who_proc_1_svc(void *, struct svc_req *);
extern int who_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WHO_PROC 1
extern  char ** who_proc_1();
extern  char ** who_proc_1_svc();
extern int who_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REMOTE_H_RPCGEN */
