/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_WHO_H_RPCGEN
#define _RPC_WHO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct who_entry {
	char *user;
	char *tty;
	char *host;
	long login_time;
};
typedef struct who_entry who_entry;

struct who_list {
	struct {
		u_int entries_len;
		who_entry *entries_val;
	} entries;
};
typedef struct who_list who_list;

#define WHO_PROG 0x31234567
#define WHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define WHO_PROC 1
extern  who_list * who_proc_1(void *, CLIENT *);
extern  who_list * who_proc_1_svc(void *, struct svc_req *);
extern int who_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WHO_PROC 1
extern  who_list * who_proc_1();
extern  who_list * who_proc_1_svc();
extern int who_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_who_entry (XDR *, who_entry*);
extern  bool_t xdr_who_list (XDR *, who_list*);

#else /* K&R C */
extern bool_t xdr_who_entry ();
extern bool_t xdr_who_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_WHO_H_RPCGEN */
