/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_who.h"

bool_t
xdr_who_entry (XDR *xdrs, who_entry *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tty, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->host, 256))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->login_time))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_who_list (XDR *xdrs, who_list *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->entries.entries_val, (u_int *) &objp->entries.entries_len, 64,
		sizeof (who_entry), (xdrproc_t) xdr_who_entry))
		 return FALSE;
	return TRUE;
}
